version: '3.8'
services:
  my_vnc_service:
    image: my_vnc_image # 这里需要您构建Docker镜像并为其指定一个名称
    build:
      context: . # Dockerfile所在的目录
      dockerfile: Dockerfile # Dockerfile文件的名称
    ports:
      - "8900:8900" # 映射端口，将容器的8900端口映射到宿主机的8900端口
    environment:
      - VNC_PASSWORD=luo # 如果需要，设置环境变量来传递VNC密码
    volumes:
      - ./noVNC-1.2.0:/noVNC-1.2.0 # 如果需要，挂载宿主机的目录到容器中
    command: ["/luo.sh"] # 容器启动时执行的命令
